### ISSUE TITLE
source files

### ISSUE THREAD

**Issue by alexmyczko** [warszawskie-kroje/zaklad#1]
How is the otf generated, where's the source file?

**Comment by jfcieslak** [comment]
We only have the exported files for this font, but I will contact the author and ask for the source .glyphs file if it is available.

**Comment by alexmyczko** [comment]
any news?

**Comment by jfcieslak** [comment]
Yup, got the source files in .ufo e23057817a3aee58f1cd11a214675d23d6fe39d7

**Comment by alexmyczko** [comment]
Would've been great to have a v1.1 release with it...
